export const TOKENS = {
  StorageService: Symbol.for('StorageService'),
  AuthClient: Symbol.for('AuthClient'),
  AuthRepository: Symbol.for('AuthRepository'),
  AuthStore: Symbol.for('AuthStore'),
  AuthService: Symbol.for('AuthService'),
  UserRepository: Symbol.for('UserRepository'),
  UsersService: Symbol.for('UsersService'),
  ProfileStore: Symbol.for('ProfileStore'),
  ProfileService: Symbol.for('ProfileService'),
  KeyringManager: Symbol.for('KeyringManager'),
  ChainRegistry: Symbol.for('ChainRegistry'),
  WalletStore: Symbol.for('WalletStore'),
  WalletService: Symbol.for('WalletService'),
  ExplorerService: Symbol.for('ExplorerService'),
  BiometricProvider: Symbol.for('BiometricProvider'),
  SecurityStore: Symbol.for('SecurityStore'),
  SecurityService: Symbol.for('SecurityService'),
  SettingsStore: Symbol.for('SettingsStore'),
  SettingsService: Symbol.for('SettingsService'),
  TokensService: Symbol.for('TokensService'),
  PriceProvider: Symbol.for('PriceProvider'),
  PricesStore: Symbol.for('PricesStore'),
  PricesService: Symbol.for('PricesService'),
} as const;
