export const TOKENS = {
  StorageService: Symbol.for('StorageService'),
  AuthClient: Symbol.for('AuthClient'),
  AuthRepository: Symbol.for('AuthRepository'),
  AuthStore: Symbol.for('AuthStore'),
  AuthService: Symbol.for('AuthService'),
  UserRepository: Symbol.for('UserRepository'),
  UsersService: Symbol.for('UsersService'),
  KeyringManager: Symbol.for('KeyringManager'),
  ChainRegistry: Symbol.for('ChainRegistry'),
  WalletStore: Symbol.for('WalletStore'),
  WalletService: Symbol.for('WalletService'),
  ExplorerService: Symbol.for('ExplorerService'),
  TokensService: Symbol.for('TokensService'),
} as const;
